"""GeoPSRO legacy phrase vocabulary and lexical shaping, adapted explicitly.

Source: retained GeoPSRO geopsro4d/reward/reward_fn.py delivery.
Only lexical rules are ported: answer parsing remains gold-blind in the caller.
Risk phrases are diagnostics, NOT hallucination verification or penalties.
"""
from typing import Any, Dict, Iterable, Mapping, Sequence, Set, Tuple
import re

OBSERVATION_WORDS = frozenset([
  "3d",
  "adjacent",
  "aligned",
  "alignment",
  "anchor",
  "anchor object",
  "angle",
  "apparent size",
  "appear",
  "appearance",
  "appears",
  "area",
  "arrangement",
  "as observed",
  "as shown",
  "as visible",
  "back side",
  "background",
  "based on the frame",
  "based on the image",
  "blocked",
  "boundary",
  "camera view",
  "ceiling",
  "centered",
  "central",
  "clear",
  "clearly",
  "clip",
  "configuration",
  "context",
  "corner",
  "covered",
  "depict",
  "depicted",
  "depth",
  "depth cue",
  "depth cues",
  "display",
  "displayed",
  "distance",
  "edge",
  "entities",
  "entity",
  "environment",
  "evidently",
  "facing",
  "floor",
  "foreground",
  "frame",
  "frames",
  "from the frame",
  "from the image",
  "front side",
  "fully visible",
  "geometric",
  "geometric relation",
  "geometry",
  "ground",
  "hidden",
  "identified",
  "identify",
  "image",
  "images",
  "in the frame",
  "in the image",
  "item",
  "items",
  "key evidence",
  "landmark",
  "layout",
  "layout relation",
  "left side",
  "line of sight",
  "located",
  "location",
  "lower side",
  "lying",
  "middle",
  "midground",
  "nearby",
  "object",
  "object relation",
  "objects",
  "observation",
  "observe",
  "observed",
  "occluded",
  "occlusion",
  "orientation",
  "oriented",
  "overlapping",
  "part",
  "partially visible",
  "perspective",
  "placed",
  "placement",
  "plane",
  "position",
  "positional relation",
  "positioned",
  "presence",
  "present",
  "projection",
  "reference",
  "reference object",
  "region",
  "relation",
  "relationship",
  "relative",
  "relative distance",
  "relative position",
  "relative relation",
  "relevant evidence",
  "resting",
  "right side",
  "room",
  "scale",
  "scene",
  "scene layout",
  "see",
  "seen",
  "sequence",
  "shape",
  "show",
  "shown",
  "shows",
  "side",
  "sitting",
  "situated",
  "size",
  "spatial",
  "spatial cue",
  "spatial evidence",
  "spatial layout",
  "spatial relation",
  "spatial relationship",
  "standing",
  "structure",
  "surface",
  "surroundings",
  "target",
  "target object",
  "three-dimensional",
  "upper side",
  "video",
  "view",
  "view geometry",
  "viewed",
  "viewpoint",
  "visibility",
  "visible",
  "visible evidence",
  "visible object",
  "visibly",
  "visual context",
  "visual cue",
  "visual cues",
  "visual evidence",
  "visual input",
  "visually",
  "wall",
  "within the scene"
])

SPATIAL_RELATION_WORDS = frozenset([
  "above",
  "across",
  "adjacent",
  "against",
  "ahead",
  "aligned",
  "along",
  "among",
  "around",
  "away",
  "away from",
  "back",
  "backward",
  "behind",
  "below",
  "beneath",
  "beside",
  "between",
  "boundary",
  "center",
  "central",
  "close",
  "close to",
  "closer",
  "connected",
  "contact",
  "contained",
  "corner",
  "diagonal",
  "different relation",
  "direction",
  "distance",
  "distant",
  "downward",
  "edge",
  "facing",
  "facing away",
  "facing toward",
  "far",
  "farther",
  "forward",
  "front",
  "gap",
  "geometric relation",
  "height",
  "higher",
  "horizontal",
  "in front",
  "in front of",
  "inside",
  "layout relation",
  "left",
  "left side",
  "leftward",
  "lower",
  "middle",
  "near",
  "nearby",
  "nearer",
  "next to",
  "on the left",
  "on the right",
  "on top of",
  "opposite",
  "orientation",
  "outside",
  "over",
  "overlapping",
  "parallel",
  "perpendicular",
  "pose",
  "positional relation",
  "proximity",
  "rear",
  "relation changes",
  "relation remains",
  "relative distance",
  "relative position",
  "right",
  "right side",
  "rightward",
  "same relation",
  "same side",
  "separated",
  "separation",
  "side",
  "spatial arrangement",
  "spatial configuration",
  "spatial relation",
  "spatial relationship",
  "surrounded",
  "to the left",
  "to the right",
  "touching",
  "toward",
  "under",
  "underneath",
  "upper",
  "upward",
  "vertical",
  "within"
])

TRANSITION_WORDS = frozenset([
  "across frames",
  "after",
  "agent moves",
  "angle change",
  "appear",
  "appears",
  "approach",
  "approaches",
  "becomes",
  "becomes closer",
  "becomes farther",
  "becomes hidden",
  "becomes visible",
  "before",
  "between frames",
  "blocked",
  "camera",
  "camera angle",
  "camera motion",
  "camera moved",
  "camera moves",
  "camera view",
  "change",
  "changed",
  "changes",
  "changes side",
  "consistent",
  "continues",
  "continuity",
  "covered",
  "cross-frame",
  "current state",
  "disappear",
  "disappears",
  "displacement",
  "does not change",
  "during",
  "earlier",
  "ego-motion",
  "enters",
  "enters view",
  "field of view",
  "finally",
  "first",
  "following",
  "frame to frame",
  "from frame",
  "gets closer",
  "gets farther",
  "in the earlier frame",
  "in the first frame",
  "in the later frame",
  "in the next frame",
  "initially",
  "inter-frame",
  "later",
  "later state",
  "layout changes",
  "leaves",
  "leaves view",
  "maintained",
  "motion",
  "move",
  "move away",
  "move closer",
  "moved",
  "movement",
  "moves",
  "moves backward",
  "moves behind",
  "moves closer",
  "moves forward",
  "moves in front",
  "moves left",
  "moves right",
  "moves to the left",
  "moves to the right",
  "multi-frame",
  "next",
  "no change",
  "observer moves",
  "occluded",
  "occlusion",
  "over the frames",
  "over time",
  "pan",
  "path",
  "perspective",
  "perspective shift",
  "position changes",
  "position remains",
  "preserved",
  "previous",
  "previous state",
  "progression",
  "reappear",
  "relation changes",
  "relation holds",
  "relation is preserved",
  "relation remains",
  "relative position changes",
  "relative position remains",
  "remain",
  "remained",
  "remains",
  "revealed",
  "rotate",
  "rotates",
  "rotation",
  "same",
  "same position",
  "same relation",
  "same side",
  "second",
  "sequence",
  "sequential",
  "shift",
  "shifts",
  "shifts left",
  "shifts right",
  "spatial change",
  "spatial continuity",
  "spatial state",
  "stable",
  "state change",
  "state continuity",
  "state evolution",
  "still",
  "still visible",
  "subsequent",
  "temporal",
  "then",
  "third",
  "through the frames",
  "tilt",
  "to frame",
  "trajectory",
  "transition",
  "transitions",
  "turn",
  "turned",
  "turns",
  "unchanged",
  "view",
  "view change",
  "viewpoint",
  "viewpoint change",
  "viewpoints",
  "views",
  "visibility changes",
  "visible again",
  "visual sequence",
  "while",
  "zoom"
])

DERIVATION_WORDS = frozenset([
  "above",
  "according to",
  "aligned with",
  "answer",
  "as a result",
  "based on",
  "based on the observation",
  "based on the transition",
  "because",
  "behind",
  "below",
  "best matches",
  "choice",
  "choose",
  "chosen",
  "conclude",
  "conclusion",
  "confirms",
  "consistent with",
  "correct answer",
  "correct choice",
  "cue",
  "cues",
  "decide",
  "decision",
  "deduce",
  "deduced",
  "derivation",
  "derive",
  "derived",
  "derived from",
  "determine",
  "determined",
  "different",
  "due to",
  "evidence",
  "far",
  "final answer",
  "follows from",
  "for this reason",
  "from these observations",
  "from this",
  "front",
  "given",
  "hence",
  "identify",
  "implies",
  "infer",
  "inference",
  "inferred",
  "inside",
  "instead of",
  "is correct",
  "is supported",
  "judge",
  "leads to",
  "left",
  "letter",
  "matches",
  "most consistent",
  "must be",
  "near",
  "no",
  "option",
  "outside",
  "points to",
  "rather than",
  "reason",
  "reasoning",
  "right",
  "same",
  "select",
  "selected",
  "selected option",
  "since",
  "so",
  "spatial evidence",
  "supported by",
  "supports",
  "the answer",
  "therefore",
  "this indicates",
  "this means",
  "this shows",
  "this supports",
  "thus",
  "visual evidence",
  "yes"
])

EVIDENCE_GEOMETRY_WORDS = frozenset([
  "3d",
  "agrees",
  "aligned",
  "alignment",
  "camera cue",
  "camera geometry",
  "camera pose",
  "compare",
  "compared",
  "comparison",
  "confirms",
  "consistency",
  "consistent",
  "continuity",
  "continuous",
  "correspondence",
  "cross-check",
  "cross-frame consistency",
  "depth",
  "depth cue",
  "distance",
  "evidence",
  "field of view",
  "frame evidence",
  "geometric",
  "geometric consistency",
  "geometric continuity",
  "geometric cue",
  "geometric evidence",
  "geometry",
  "grounded",
  "image evidence",
  "layout cue",
  "line of sight",
  "matches",
  "matching",
  "motion cue",
  "multi-frame consistency",
  "observed evidence",
  "occlusion",
  "occlusion cue",
  "parallax",
  "perspective",
  "perspective cue",
  "plane",
  "pose",
  "projection",
  "relation consistency",
  "relation cue",
  "relative distance",
  "relative scale",
  "same object",
  "same relation",
  "same state",
  "scale",
  "scene structure",
  "shape",
  "spatial consistency",
  "spatial continuity",
  "spatial cue",
  "spatial evidence",
  "spatial layout",
  "spatially grounded",
  "stable position",
  "stable relation",
  "state consistency",
  "supported",
  "supporting evidence",
  "surface",
  "temporal consistency",
  "three-dimensional",
  "topology",
  "validate",
  "verifies",
  "view cue",
  "view geometry",
  "viewpoint",
  "visibility",
  "visible cue",
  "visual consistency",
  "visual evidence",
  "visually grounded"
])

UNSUPPORTED_RISK_WORDS = frozenset([
  "appears to",
  "assume",
  "assumption",
  "cannot determine",
  "could be",
  "guess",
  "i cannot see",
  "maybe",
  "might",
  "not enough information",
  "not in the image",
  "not provided",
  "not shown",
  "not visible",
  "possibly",
  "probably",
  "seems",
  "uncertain",
  "unclear",
  "unknown",
  "unsupported"
])

def _clip(value: float, lo: float = 0.0, hi: float = 1.0) -> float:
    return max(lo, min(hi, float(value)))

def _normalize_text(text: Any) -> str:
    text = str(text or "").lower()
    text = text.replace("\u2019", "'")
    text = re.sub(r"<[^>]+>", " ", text)
    text = re.sub(r"[^a-z0-9.+\-\u4e00-\u9fff]+", " ", text)
    return re.sub(r"\s+", " ", text).strip()

def _boundary_contains(text: str, phrase: str) -> bool:
    if not phrase:
        return False
    # Explicit safety adaptation: phrases also require word boundaries.
    return re.search(rf"(?<!\w){re.escape(phrase)}(?!\w)", text) is not None

def _unique_phrase_hits(text: Any, vocab: Iterable[str]) -> Set[str]:
    norm = _normalize_text(text)
    hits: Set[str] = set()
    for phrase in sorted(vocab, key=len, reverse=True):
        phrase_norm = _normalize_text(phrase)
        if _boundary_contains(norm, phrase_norm):
            hits.add(phrase)
    return hits

def _count_all_phrase_hits(text: Any, vocabs: Sequence[Iterable[str]]) -> int:
    norm = _normalize_text(text)
    count = 0
    for vocab in vocabs:
        for phrase in vocab:
            phrase_norm = _normalize_text(phrase)
            if not phrase_norm:
                continue
            count += len(re.findall(rf"(?<!\w){re.escape(phrase_norm)}(?!\w)", norm))
    return count

def _looks_like_word_list(text: Any) -> bool:
    norm = _normalize_text(text)
    comma_parts = [part.strip() for part in str(text or "").lower().split(",") if part.strip()]
    if len(comma_parts) >= 12:
        avg_len = sum(len(part.split()) for part in comma_parts) / max(len(comma_parts), 1)
        if avg_len <= 3:
            return True
    sentence_marks = sum(norm.count(mark) for mark in (".", ";", " because ", " since ", " therefore ", " so "))
    word_count = len(norm.split())
    return word_count >= 30 and sentence_marks == 0 and len(comma_parts) >= 8

def _section_looks_like_vocab_list(text: Any, hits: Set[str]) -> bool:
    norm = _normalize_text(text)
    words = [word for word in norm.split() if word]
    if len(words) < 6 or len(hits) < 5:
        return False
    unique_words = set(words)
    hit_ratio = len({_normalize_text(hit) for hit in hits}) / max(1, len(unique_words))
    sentence_cues = {
        "the",
        "a",
        "an",
        "is",
        "are",
        "was",
        "were",
        "in",
        "of",
        "to",
        "while",
        "since",
        "because",
        "therefore",
    }
    cue_count = sum(1 for cue in sentence_cues if cue in unique_words)
    return hit_ratio >= 0.65 and cue_count <= 2

def _words_score(parsed: Mapping[str, Any], answer_score: float) -> Tuple[float, Dict[str, float]]:
    if answer_score < 1.0:
        return 0.0, {
            "words_observation": 0.0,
            "words_transition": 0.0,
            "words_derivation": 0.0,
            "words_relation": 0.0,
            "words_evidence": 0.0,
            "words_unique_hits": 0.0,
            "words_total_hits": 0.0,
            "words_unsupported_hits": 0.0,
        }

    observation = str(parsed.get("observation", ""))
    transition = str(parsed.get("transition", ""))
    derivation = str(parsed.get("derivation", ""))
    think = str(parsed.get("raw_think", ""))

    obs_hits = _unique_phrase_hits(observation, OBSERVATION_WORDS)
    trans_hits = _unique_phrase_hits(transition, TRANSITION_WORDS)
    deriv_hits = _unique_phrase_hits(derivation, DERIVATION_WORDS)
    relation_hits = _unique_phrase_hits(think, SPATIAL_RELATION_WORDS)
    evidence_hits = _unique_phrase_hits(think, EVIDENCE_GEOMETRY_WORDS)
    unsupported_hits = _unique_phrase_hits(think, UNSUPPORTED_RISK_WORDS)

    obs_score = min(len(obs_hits) / 5.0, 1.0)
    trans_score = min(len(trans_hits) / 5.0, 1.0)
    deriv_score = min(len(deriv_hits) / 4.0, 1.0)
    relation_score = min(len(relation_hits) / 4.0, 1.0)
    evidence_score = min(len(evidence_hits) / 3.0, 1.0)

    words_score = (
        0.24 * obs_score
        + 0.28 * trans_score
        + 0.22 * deriv_score
        + 0.16 * relation_score
        + 0.10 * evidence_score
    )

    all_unique = obs_hits | trans_hits | deriv_hits | relation_hits | evidence_hits
    total_hits = _count_all_phrase_hits(
        think,
        [OBSERVATION_WORDS, TRANSITION_WORDS, DERIVATION_WORDS, SPATIAL_RELATION_WORDS, EVIDENCE_GEOMETRY_WORDS],
    )
    vocab_list_sections = sum(
        (
            _section_looks_like_vocab_list(observation, obs_hits),
            _section_looks_like_vocab_list(transition, trans_hits),
            _section_looks_like_vocab_list(derivation, deriv_hits),
        )
    )
    if total_hits >= 20 and len(all_unique) <= 6:
        words_score = 0.0
    if vocab_list_sections >= 2:
        words_score = 0.0
    if _looks_like_word_list(think):
        words_score = 0.0

    return _clip(words_score), {
        "words_observation": float(obs_score),
        "words_transition": float(trans_score),
        "words_derivation": float(deriv_score),
        "words_relation": float(relation_score),
        "words_evidence": float(evidence_score),
        "words_unique_hits": float(len(all_unique)),
        "words_total_hits": float(total_hits),
        "words_unsupported_hits": float(len(unsupported_hits)),
    }

def legacy_words_score(fields, answer_score):
    """Keep original five-category thresholds, gates and anti-stuffing rules."""
    names = ("Spatial Observation", "Spatial Transition", "Answer Derivation")
    parsed = dict(zip(("observation", "transition", "derivation"), (fields.get(n, "") for n in names)))
    parsed["raw_think"] = "\n".join(n + ": " + fields.get(n, "") for n in names)
    return _words_score(parsed, answer_score)
